### ISSUE TITLE
table package update throws errors

### ISSUE THREAD

**Issue by Ephigenia** [Ephigenia/mite-cli#159]
## Context

Trying to update the "table" package to latest 6.7.0 version.

## Description

When the package is updated, there are errors thrown when running `mite list`:

```
  {
    message: 'must NOT have additional properties',
    params: { additionalProperty: 'attribute' },
    schemaPath: '#/additionalProperties'
  },
  {
    message: 'must NOT have additional properties',
    params: { additionalProperty: 'format' },
    schemaPath: '#/additionalProperties'
  },
  {
    message: 'must match exactly one schema in oneOf',
    params: { passingSchemas: null },
    schemaPath: '#/oneOf'
  }
]
/Users/ephigenia/Development/mite-cli/node_modules/table/dist/validateConfig.js:22
        throw new Error('Invalid config.');
        ^

Error: Invalid config.
    at Object.validateConfig (/Users/ephigenia/Development/mite-cli/node_modules/table/dist/validateConfig.js:22:15)
    at Object.makeTableConfig (/Users/ephigenia/Development/mite-cli/node_modules/table/dist/makeTableConfig.js:50:22)
    at table (/Users/ephigenia/Development/mite-cli/node_modules/table/dist/table.js:17:38)
    at Object.formatData (/Users/ephigenia/Development/mite-cli/source/lib/data-output.js:147:14)
    at getReport (/Users/ephigenia/Development/mite-cli/source/mite-list.js:234:21)
    at /Users/ephigenia/Development/mite-cli/source/mite-list.js:262:20
    at handleResponse (/Users/ephigenia/Development/mite-cli/node_modules/mite-api/lib/mite-api.js:77:14)
    at Request._callback (/Users/ephigenia/Development/mite-cli/node_modules/mite-api/lib/mite-api.js:95:16)
    at Request.self.callback (/Users/ephigenia/Development/mite-cli/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
```

## Possible Solution

- find correct use of failing properties

**Comment by Ephigenia** [comment]
fixed in 1.8.1
